### ISSUE TITLE
Plugin Dev

### ISSUE THREAD

**Issue by mantorok1** [homebridge-plugins/homebridge-rainbird#1]
Hi @donavanbecker, I thought it may be better to move the conversation to your repo.

I didn't realise you'd already made good progress on this. Do you have a RainBird yourself? Which model?

I did make a start last weekend and managed to get some connectivity to my RainBird. I was able to retrieve the model, serial number, zones and the current status.

From googling around I found this: https://github.com/homebridge/homebridge/issues/1707#issuecomment-486418630
So my understanding is that I need to create an irrigation system accessory and then a valve accessory for each zone. The valves are then added as linked services to the irrigation system.

I gave that a go but I couldn't get it to look like the screenshot in the above link. That was 2 or 3 years ago so maybe Apple changed the UI in the Home app.

I'm happy to collaborate on this if you like.

**Comment by donavanbecker** [comment]
Creating this for a relative. So need to get the model. 

Also, yes, let's collaborate. I can add you as a collaborator onto this plugin if you want? 

Also are you on the homebridge discord server?

**Comment by donavanbecker** [comment]
ESP-TM2

**Comment by mantorok1** [comment]
Cool. That's the same model I have.

Thanks for the invite which I've accepted. Is there anything in particular you'd like me to focus on?

Also, I am on Homebridge Discord server, my username is `Mantorok`. I haven't used it much though

**Comment by donavanbecker** [comment]
@mantorok1 Since I don't have the unit right in front of me. Go ahead and push any changes you want into the beta branch. And commit that is pushed will publish a new beta version on npm.

**Comment by mantorok1** [comment]
No worries. I'm hoping to have some spare time this weekend to focus on this.

For the first release are you thinking of just supporting turning on a zone for a set duration?

**Comment by donavanbecker** [comment]
> No worries. I'm hoping to have some spare time this weekend to focus on this.
> 
> For the first release are you thinking of just supporting turning on a zone for a set duration?

yeah that works. I think get the plugin going and then we can go from there.

**Comment by mantorok1** [comment]
Hi @donavanbecker, I just pushed a change to the `beta` branch. The main changes are:

- replacement of node-rainbird with my RainBirdClient
- Use of Irrigation System accessory with valves for each zone

When activating a zone in the Home app that zone should start and deactivating should turn it off.

It's still very rough with a number of issues:

- After restarting Homebridge the Firmware version gets set to the plugin version not the version from the rainbird API
- Activating another zone will kill the current zone
- Home app only seems to allow a duration of either 5 or 10 minutes
- The on/off slider doesn't automatically go back to the off state at the end of the specified duration
- The Irrigation accessory remains in the "Off" state even though a valve is active
- Valve shows it's in a waiting state even though the sprinter is active

**Comment by donavanbecker** [comment]
@mantorok1 Awesome!! I will look at those issues, and see if I can help resolve them.

**Comment by mantorok1** [comment]
@donavanbecker, I just pushed another commit. I added a queuing system for the zones so if you turn on multiple zones they will operate in sequence. This overcomes the issue where starting one zone will stop another. It should now display the correct states and show the remaining time left for a zone.

I think we're getting very close now...

**Comment by mantorok1** [comment]
Looks like that 5 or 10 min duration limitation is a bug in iOS 14. See https://github.com/homebridge/HAP-NodeJS/issues/857
It works correctly in the macOS Home app

**Comment by donavanbecker** [comment]
> @donavanbecker, I just pushed another commit. I added a queuing system for the zones so if you turn on multiple zones they will operate in sequence. This overcomes the issue where starting one zone will stop another. It should now display the correct states and show the remaining time left for a zone.
> 
> 
> 
> I think we're getting very close now...

I am going to test again and the push out 0.1.0, for testing purposes before we release 1.0.0! Thanks for your work on this! By chance can we refactor all of the irrigation code to the irrigation file?

**Comment by mantorok1** [comment]
Yeah, I don't mind. I was just following the pattern from the Orbit plugin. You're welcome to refactor it to however you like

**Comment by donavanbecker** [comment]
@mantorok1 looking over this, I am not seeing the ipaddress or password being used from the config?

**Comment by mantorok1** [comment]
They are passed into the constructor of the RainBirdClient:
```
this.rainbird = new RainBirdClient(this.config.ipaddress!, this.config.password!, this.log);
```
See line 54 of platform.ts

**Comment by donavanbecker** [comment]
> They are passed into the constructor of the RainBirdClient:
> 
> ```
> this.rainbird = new RainBirdClient(this.config.ipaddress!, this.config.password!, this.log);
> ```
> 
> See line 54 of platform.ts

thanks! Yeah I figured that out after a little bit... haha I am refactoring right now, going to take a little bit, Also adding the config of `device.ipaddress` and `device.password`. In an array so that if anyone is in a situation where they have multiple controllers, it would be able to handle both controllers.

**Comment by donavanbecker** [comment]
@mantorok1 I am going to close this now that I have added you on Discord Server.
