### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by larrysharon** [homebridge-plugins/homebridge-rainbird#157]
### Describe Your Problem

Can't Add Device In Plugin

### Config for homebridge-rainbird

```shell
{
            "name": "RainBird",
            "devices": [
                {
                    "ipaddress": "192.168.0.143",
                    "password": "Abby1984",
                    "showStopIrrigationSwitch": true,
                    "logging": "debug"
                }
            ],
            "platform": "RainBird"
        }
```

### Screenshots

<img width="902" alt="Screen Shot 2022-01-30 at 12 11 10 PM" src="https://user-images.githubusercontent.com/6014612/151709961-07fafbfc-4b50-4839-b66b-18448637c31e.png">

### Device & Model

ESP-TM2

### Node.js Version

v16.13.2

### NPM Version

v8.1.2

### Homebridge Version

v1.4.0

### Homebridge Rainbird Plugin Version

v1.6.1

### Homebridge Config UI X Plugin Version

v4.42.0

### Operating System

Docker

**Comment by larrysharon** [comment]
[homebridge.log.txt](https://github.com/donavanbecker/homebridge-rainbird/files/7966475/homebridge.log.txt)

**Comment by mantorok1** [comment]
Hi @larrysharon,

That error usually indicates that the plugin sent a request to the Rainbird controller but received no timely response. Does the Rain Bird app have any issues connecting to the controller?

You can try testing the connection from Homebridge UI's terminal with the following command:
```
nc -vz 192.168.0.143 80
```
