### ISSUE TITLE
Not Ready for Testing

### ISSUE THREAD

**Issue by iondarie** [homebridge-plugins/homebridge-rainbird#2]
Hello,

I have installed your plugin, but i am stuck on the 3'rd step on the configuration page: "and enter the 'Callback URL' exactly as it is displayed below." and the input box below is empty.

Please see attached screenshot.

Thank you,

![Screenshot 2021-08-26 at 15 46 05](https://user-images.githubusercontent.com/9055885/130965629-1f037cf7-8563-4078-ab4d-a0fc175b9891.png)

**Comment by donavanbecker** [comment]
this plugin is a work in progress. this page is not complete and I have release a new beta that removes these steps. 

`v0.0.2-beta.5`
