### ISSUE TITLE
Bug: Home app not showing any of the sprinklers

### ISSUE THREAD

**Issue by onelight17** [homebridge-plugins/homebridge-rainbird#200]
### Describe The Bug

Before all the zones would show in the home app. Now when I click the accessory it is just a blank page

### To Reproduce

Open sprinkler accessory in Apple Home app. Blank white screen

### Expected behavior

Should have shown the individual zones. (They show up in HomeBridge)

### Relevant log output

```shell
[3/18/2022, 3:15:36 PM] [RainBird] Adding new accessory: ESP-TM2
[3/18/2022, 3:15:36 PM] [RainBird] Leak Sensor: ESP-TM2 Config: {"ipaddress":"xxxx","password":"xxx","showRainSensor":true,"showValveSensor":true,"showProgramASwitch":true,"showProgramBSwitch":true,"showProgramCSwitch":true,"showRequestResponse":true,"logging":"standard","showStopIrrigationSwitch":false}
[3/18/2022, 3:15:36 PM] [RainBird] Adding new accessory: WR2
[3/18/2022, 3:15:36 PM] [RainBird] Adding new accessory: ESP-TM2-1
[3/18/2022, 3:15:36 PM] [RainBird] Adding new accessory: ESP-TM2-2
[3/18/2022, 3:15:36 PM] [RainBird] Adding new accessory: ESP-TM2-3
[3/18/2022, 3:15:36 PM] [RainBird] Adding new accessory: ESP-TM2-4
[3/18/2022, 3:15:36 PM] [RainBird] Adding new accessory: ESP-TM2-5
[3/18/2022, 3:15:36 PM] [RainBird] Adding new accessory: ESP-TM2-6
[3/18/2022, 3:15:36 PM] [RainBird] Adding new accessory: ESP-TM2-7
[3/18/2022, 3:15:36 PM] [RainBird] Adding new accessory: ESP-TM2-8
[3/18/2022, 3:15:36 PM] [RainBird] Adding new accessory: ESP-TM2-pgm-A
[3/18/2022, 3:15:36 PM] [RainBird] Adding new accessory: ESP-TM2-pgm-B
[3/18/2022, 3:15:36 PM] [RainBird] Adding new accessory: ESP-TM2-pgm-C
```

### Config for homebridge-rainbird

```shell
{
            "name": "RainBird",
            "devices": [
                {
                    "ipaddress": "xxx",
                    "password": "xxx",
                    "showRainSensor": true,
                    "showValveSensor": true,
                    "showProgramASwitch": true,
                    "showProgramBSwitch": true,
                    "showProgramCSwitch": true,
                    "showRequestResponse": true,
                    "logging": "standard"
                }
            ],
            "options": {
                "refreshRate": 120
            },
            "disablePlugin": false,
            "platform": "RainBird",
            "_bridge": {
                "username": "xxx",
                "port": 31046
            }
        },
```

### Screenshots

![image](https://user-images.githubusercontent.com/7798848/159078557-62275062-9597-4a6a-bd7a-6c4352de9e14.png)
![image](https://user-images.githubusercontent.com/7798848/159078953-5fdea329-6273-4b49-9c8d-9bf11149de79.png)

### Device & Model

iPhone 13 Pro

### Node.js Version

v14.19.0

### NPM Version

v6.14.16

### Homebridge Version

v1.4.0

### Homebridge Rainbird Plugin Version

v1.6.2

### Operating System

Ubuntu

**Comment by onelight17** [comment]
I just tried this on an iPad running an older version of the OS and it still shows there so maybe this is a 15.4 issue?

**Comment by mantorok1** [comment]
Hi @onelight17, I was able to replicate the issue (sprinkler zone switches not showing) when I upgraded my iPad to iPadOS 15.4. So it does look like Apple broke something in version 15.4.
I need to figure out if its just the RainBird plugin that has this issue or all Irrigation systems in HomeKit.

@donavanbecker, you have a different make of an irrigation system that supports HomeKit don't you? Does the same thing happen for that?

UPDATE: I upgraded my MacBook to Monterey 12.3 and it has the same issue. For version 12.2.1 it was working ok.

**Comment by onelight17** [comment]
Oh interesting, yes I see that with Monterey 12.3 as well. Looks like Apple changed something. I don’t have any other irrigation system to test with

**Comment by donavanbecker** [comment]
This is also an issue with native HomeKit Irrigation systems.

**Comment by dan1916** [comment]
I can also confirm that this issue happens in iPhone 13 with iOS 15.4

**Comment by mantorok1** [comment]
I'm currently developing a workaround for this issue. A new config option will allow you to create each sprinkler zone as it's own accessory. Early tests are promising so hoping to release a beta tomorrow

**Comment by mantorok1** [comment]
@onelight17 @dan1916 There's a new beta (1.6.5-beta.0) which will workaround the above issue by creating separate valve accessories for each zone (it needs to be enabled in the Settings - "Show Zones as Valve Accessories"). Let me know how it goes.

**Comment by lindekai** [comment]
With a simple click on my iPhone (13ProMax iOS 15.4), I also do not see any zones. But if I press the icon longer or harder, I see all the zones that have been set up. Hope this helps with troubleshooting. (homebridge v1.4.0, node.js v16.14.2)
![image](https://user-images.githubusercontent.com/4020883/160920635-d84c55d0-ccfa-47db-9459-341a9c459ac2.png)

**Comment by mantorok1** [comment]
Thanks @lindekai, I too can get the zones to show intermittently - sometimes its a short tap other times its a long tap. Have you tried the new beta version which allows you to show the zones as their own accessories in the Home app? This allows you to better control your zones until Apple hopefully fix the bug.

**Comment by lindekai** [comment]
No but I will still try. By the way, on the iPad I get the zones displayed with double tap. (homebridge-rainbird v1.6.4)
