### ISSUE TITLE
Bug: Homekit ESP-ME Switcher array invisible 

### ISSUE THREAD

**Issue by akustikrausch** [homebridge-plugins/homebridge-rainbird#238]
### Describe The Bug

ESP-ME Switcher array not visible

### To Reproduce

Open Home App, Select ESP-Me Switcher, List of all switcher should appear. but the list is just empty.Only sometimes, after many many attempts, the switches are displayed. Not concretely reproducible

### Expected behavior

Array of switcher should be visible to be able to control the system

### Relevant log output

```shell
Plugin 1.7.1
iOS 15.4.1
but looks the same on MacOS
No difference on 2nd Phone
```

### Config for homebridge-rainbird

```shell
{
            "name": "RainBird",
            "devices": [
                {
                    "ipaddress": "192.168.xxxx",
                    "password": "",
                    "showRainSensor": true,
                    "showValveSensor": true,
                    "showStopIrrigationSwitch": true
                }
            ],
            "disablePlugin": false,
            "platform": "RainBird"
        }
```

### Screenshots

![IMG_EBA31399C89A-1](https://user-images.githubusercontent.com/95188773/166883330-db856f72-b27a-4808-9f09-1669c35209d3.jpeg)

### Device & Model

iphone 13Pro, 15.4.1

### Node.js Version

16.15.0

### NPM Version

8.9.0

### Homebridge Version

1.4.1

### Homebridge Rainbird Plugin Version

1.7.1

### Homebridge Config UI X Plugin Version

4.43.2

### Operating System

all

**Comment by mantorok1** [comment]
Hi @akustikrausch,

This is a known bug (see [issue #200](https://github.com/donavanbecker/homebridge-rainbird/issues/200))

In summary:
- Apple introduced a bug in iOS 15.4 & macOS 12.3 which can cause the zone switches to be invisible
- To workaround this issue a new option was added to the plugin ("Show Zones as Valve Accessories"). With this option enabled it will show a separate Valve Switch in the Home app for each RainBird zone you have.

Hope that helps you out.
