### ISSUE TITLE
Support Request: Scheduled at the time different area

### ISSUE THREAD

**Issue by zifou2015** [homebridge-plugins/homebridge-rainbird#277]
### Describe Your Problem

schedule at time

### Relevant log output

```shell
I have a question concerning my plugin Rainbird

Its possible to schedule at time specific my different zone area with my homekit ????

I already adding my plugin in my homebridge, everything is ok, if i start or stop my different zone area,
```

### Device & Model

RZXE

### Node.js Version

V14.4

### NPM Version

V7.20.5

### Homebridge Version

last

### Homebridge Rainbird Plugin Version

last

### Operating System

Mac OS

**Comment by mantorok1** [comment]
Hi @zifou2015, I don't think the HomeKit Irrigation System accessory supports schedules but you may be able to achieve the same thing using HomeKit automations

**Comment by zifou2015** [comment]
Hello,

No its impossible to use Homekit automations wtih Rainbird plugin.
Normally i have for each plugin homekit "menu add Automations" (i can choose hour .....) , but for this plugin i dont have this menu.
I can only activate manually start and stop.

Thanks

________________________________
De : mantorok1 ***@***.***>
Envoyé : lundi 20 juin 2022 08:55
À : donavanbecker/homebridge-rainbird ***@***.***>
Cc : zifou2015 ***@***.***>; Mention ***@***.***>
Objet : Re: [donavanbecker/homebridge-rainbird] Support Request: Scheduled at the time different area (Issue #277)


Hi @zifou2015<https://github.com/zifou2015>, I don't think the HomeKit Irrigation System accessory supports schedules but you may be able to achieve the same thing using HomeKit automations

**Comment by mantorok1** [comment]
Yeah it looks like the Home app doesn't support creating automations for Valve accessories.
Personally I just use the RainBird app on my iPhone to schedule my zones

**Comment by zifou2015** [comment]
OK , i will use Rainbird app
________________________________
De : mantorok1 ***@***.***>
Envoyé : lundi 20 juin 2022 09:51
À : donavanbecker/homebridge-rainbird ***@***.***>
Cc : zifou2015 ***@***.***>; Mention ***@***.***>
Objet : Re: [donavanbecker/homebridge-rainbird] Support Request: Scheduled at the time different area (Issue #277)


Yeah it looks like the Home app doesn't support creating automations for Valve accessories.
Personally I just use the RainBird app on my iPhone to schedule my zones
