### ISSUE TITLE
Feature Request: Show Current Status in HomeKit

### ISSUE THREAD

**Issue by kukacwap** [homebridge-plugins/homebridge-rainbird#28]
### Describe The Bug

HomeKit won't show running watering if started from Rainbird App or its scheduler

### To Reproduce

start a watering program from the app

### Expected behavior

It would switch to running in HK (with remaining time and zones in waiting).

### Relevant log output

```shell
no logs showing up
```

### Config for homebridge-rainbird

```shell
{
            "name": "RainBird",
            "ipaddress": "removed",
            "password": "removed",
            "options": {
                "refreshRate": 120,
                "thermostat": {
                    "thermostatSetpointStatus": "PermanentHold"
                },
                "roompriority": {
                    "priorityType": "PickARoom"
                }
            },
            "devicediscovery": true,
            "platform": "RainBird"
        }
```

### Device & Model

ESP-TM2

### Node.js Version

v14.17.6

### NPM Version

v6.14.15

### Homebridge Version

1.3.4

### Homebridge Rainbird Plugin Version

0.1.0

### Operating System

Raspbian

**Comment by mantorok1** [comment]
I'm currently working on an enhancement that will retrieve the controller's status and show the currently active zone in HomeKit

**Comment by donavanbecker** [comment]
Thanks to @mantorok1, this is now in the current beta

**Comment by donavanbecker** [comment]
v1.0.0 has been released.
