### ISSUE TITLE
Callback URL missing

### ISSUE THREAD

**Issue by sunchaser360** [homebridge-plugins/homebridge-rainbird#3]
Hi,

first of all thank you for making this happen! this a long awaited plugin and I'm looking forward using it.
I own a Rainbird ESP-RZXe with Wifi Module.
When I installed the plugin and try to configure it, the callback URL is missing (this is what I would need for the Honeywell Home Account). What I'm doing wrong?

Thanks
J/

**Comment by donavanbecker** [comment]
@sunchaser360 Plugin is not in a working state. And is currently only able to connect to the controller and nothing else. I will release a new update that Removes that

**Comment by sunchaser360** [comment]
Yes I realized that now also. Ok then I will wait patiently...let me know if you need sb. to test!
thx
J/

**Comment by donavanbecker** [comment]
0.0.2 is release which doesn't have that. but still not working.

**Comment by donavanbecker** [comment]
@sunchaser360 Can you try the latest beta?

**Comment by sunchaser360** [comment]
Hi, tried it today and it works! many thanks so far! now I have to figure out how to schedule the zones.

![image](https://user-images.githubusercontent.com/89637487/131333543-5ecad743-aa9a-450b-8af7-d008e1b56ecb.png)

**Comment by sunchaser360** [comment]
...ok seems to be normal by Homkit that you cannot schedule this....too bad. Maybe there is an additional Option to present the valves/zones as switches then you can add an automation on it. This would be perfect!

**Comment by donavanbecker** [comment]
> ...ok seems to be normal by Homkit that you cannot schedule this....too bad. Maybe there is an additional Option to present the valves/zones as switches then you can add an automation on it. This would be perfect!

Submit a feature request to track
