### ISSUE TITLE
Support Request:

### ISSUE THREAD

**Issue by baumph** [homebridge-plugins/homebridge-rainbird#41]
### Describe Your Problem

Getting an error that the Plugin cannot be loaded

### Relevant log output

```shell
27/09/2021, 14:42:54 [9/27/2021, 6:42:54 AM] Registering platform 'homebridge-knx.KNX'
27/09/2021, 14:42:54 [9/27/2021, 6:42:54 AM] The plugin "homebridge-rainbird" requires Node.js version of >=14.17.6 which does not satisfy the current Node.js version of v12.14.1. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
27/09/2021, 14:42:54 Error loading plugin "homebridge-rainbird"
27/09/2021, 14:42:54 Loaded plugin 'homebridge-rainbird'
27/09/2021, 14:42:54 Loaded plugin 'homebridge-webos-tv'
27/09/2021, 14:42:54 [9/27/2021, 6:42:54 AM] Registering platform 'homebridge-webos-tv.webostv'
27/09/2021, 14:42:54 Loaded plugin 'homebridge-yamaha-avr'
27/09/2021, 14:42:54 [9/27/2021, 6:42:54 AM] Registering platform 'homebridge-yamaha-avr.yamaha-avr'
27/09/2021, 14:42:54 [9/27/2021, 6:42:54 AM] The plugin "homebridge-zp" requires Node.js version of ^14.16.0 which does not satisfy the current Node.js version of v12.14.1. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
27/09/2021, 14:42:54 Loaded plugin 'homebridge-zp'
27/09/2021, 14:42:54 [9/27/2021, 6:42:54 AM] Registering platform 'homebridge-zp.Lib'
27/09/2021, 14:42:54 [9/27/2021, 6:42:54 AM] Registering platform 'homebridge-zp.ZP'
27/09/2021, 14:42:54 [9/27/2021, 6:42:54 AM] Registering platform 'homebridge-zp.ZPS1'
27/09/2021, 14:42:54 Loading 6 platforms...
27/09/2021, 14:42:54 [KNX] Initializing KNX platform...
27/09/2021, 14:42:54 ---
27/09/2021, 14:42:54 [eWeLink] Initializing eWeLink platform...
27/09/2021, 14:42:54 [eWeLink] Initialising plugin v8.3.3 | Node v12.14.1 | HB v1.3.4 | HOOBS v3...
27/09/2021, 14:42:54 [eWeLink] Config entry [debugReqRes] is unused and can be removed.
27/09/2021, 14:42:54 [eWeLink] Config entry [disableHTTPRefresh] is unused and can be removed.
27/09/2021, 14:42:54 [eWeLink] Config entry [disableEveLogging] is unused and can be removed.
27/09/2021, 14:42:54 [eWeLink] Config entry [inUsePowerThreshold] is unused and can be removed.
27/09/2021, 14:42:54 [eWeLink] Config entry [hideTHSwitch] is unused and can be removed.
27/09/2021, 14:42:54 [eWeLink] Config entry [lowBattThreshold] is unused and can be removed.
27/09/2021, 14:42:54 [eWeLink] Config entry [sensorTimeDifference] is unused and can be removed.
27/09/2021, 14:42:54 [eWeLink] Config entry [hideZBLDPress] is unused and can be removed.
27/09/2021, 14:42:54 [Küche] Initializing ZP platform...
27/09/2021, 14:42:54 [Küche] homebridge-zp v1.2.0, node v12.14.1, homebridge v1.3.4, homebridge-lib v5.1.0
27/09/2021, 14:42:54 [Küche] warning: config.json: plugin_map: invalid key
27/09/2021, 14:42:54 [Yamaha AVR] Initializing yamaha-avr platform...
27/09/2021, 14:42:54 [webostv] Initializing webostv platform...
27/09/2021, 14:42:54 Error loading platform requested in your config.json at position 6
27/09/2021, 14:42:54 Got SIGTERM, shutting down Bridge...
```

### Config for homebridge-rainbird

```shell
{
    "name": "RainBird",
    "devices": [
        {
            "ipaddress": "<removed>",
            "password": "<removed>"
        }
    ],
    "options": {
        "refreshRate": 120,
        "debug": true
    },
    "platform": "RainBird"
}
```

### Device & Model

Raspberry Pi 4

### Node.js Version

12.14.1

### NPM Version

6.13.4

### Homebridge Version

1.2.3

### Homebridge Rainbird Plugin Version

1.0.0

### Operating System

Raspian/Hoobs

**Comment by donavanbecker** [comment]
What error are you referring too? Because I am not seeing any error that would be pointing to the rainbird plugin. I do see that you are on HOOBs though and this plugin is only developed for homebridge.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

**Comment by baumph** [comment]
The initial error is fixed. I just updated NPM and Node. 

Now i am getting the error: 

[RainBird] Initializing RainBird platform...
[RainBird] "this.config.devices is not iterable

I have the controller ESP-RZXe. Is it compatible with your plugin?

**Comment by iondarie** [comment]
@baumph i have the same controller and it works

**Comment by donavanbecker** [comment]
@iondarie, are you using homebirdge or HOOBs?

**Comment by iondarie** [comment]
@donavanbecker i am using Homebridge. But hoobs is homebridge just with a nicer package

**Comment by donavanbecker** [comment]
@iondarie HOOBs is a little different than you think, it modifies Homebridge. So I that is my thought on why you aren't seeing an issue and @baumph is.

**Comment by baumph** [comment]
I have a second Raspberry Pi running standard homebridge. I am currently updating it. I´ll send an update once its finished.

**Comment by baumph** [comment]
So, i have installed the plugin on a standard homebridge install. 
I am now getting the error:

[RainBird] RainBird controller is currently OFF. Please turn ON so plugin can control it
[RainBird] Failed to Discover Devices, "Cannot read property 'getTime' of undefined"
[RainBird] [DEBUG] {}

**Comment by baumph** [comment]
Another update: 
i just hard a read through #39 and installed the Beta.
I am now getting the error: 

[RainBird] RainBird controller time 27/09/2021, 18:12:46 is more than 5 minutes fast
[RainBird] Model: ESP-RZXe, [Version: 2.9, Serial Number: 00000000000000, Zones: [1,2,3,4]]
[RainBird] Adding new accessory: ESP-RZXe
[RainBird] [DEBUG] Configure Irrigation Service
[RainBird] Failed to Discover Devices, "this.irrigation.service.getCharacteristic(...).onGet is not a function"
[RainBird] [DEBUG] {}

And still nothing is showing up in the Home app

**Comment by donavanbecker** [comment]
what is your info for your homebridge? the following error is from not being on the latest version of homebridge:

```
[RainBird] Failed to Discover Devices, "this.irrigation.service.getCharacteristic(...).onGet is not a function"
```

**Comment by baumph** [comment]
Yeah, Homebridge was outdated... Now everything works. 

Thank you very much for your help and your awesome plugin!

**Comment by donavanbecker** [comment]
@baumph Awesome!! Sorry i have no plans to support HOOBs since I only run homebridge.
