### ISSUE TITLE
Feature Request: Update Node.js

### ISSUE THREAD

**Issue by tothemoonsands** [homebridge-plugins/homebridge-rainbird#452]
### Problem

Console log warning message: The plugin "homebridge-rainbird" requires Node.js version of ^14.21.1 || ^16.18.1 || ^18.12.1 which does not satisfy the current Node.js version of v16.13.2. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF

### Solution

Update to the latest Node.js version

**Comment by donavanbecker** [comment]
You are the one that needs to update nodejs.

**Comment by donavanbecker** [comment]
Depending on how you installed Homebridge will be how you update it.

[How-To-Update-Node.js](https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js)

**Comment by tothemoonsands** [comment]
Ah got it, thank you!
