### ISSUE TITLE
Feature Request: Ignore disabled zones

### ISSUE THREAD

**Issue by tbaur** [homebridge-plugins/homebridge-rainbird#488]
### Solution

Do not enable zones that are disabled in the controller

**Comment by tbaur** [comment]
[5/22/2023, 7:19:40 PM] [RainBird] Model: ESP-ME3, [Version: 2.12, Serial Number: XXX, Zones: [1,2,3,4,5,6,7,8,9,10]]

In my controller, I have zones 9 and 10 disabled aka "Not wired" -- in the wifi app under zones, it shows a toggle for "Not wired / Wired", but the plugin still loads them. 

If possible, within the plugin, if it can ignore those disabled or not wired zones, that would be great.

**Comment by mantorok1** [comment]
Hi @tbaur,
I'm not sure if anyone has discovered the zone enabled/disabled status in the RainBird API responses. I'll have to look into it.
You can however manually do it in the iOS Home app. Zones can be set to disabled within the Irrigation System accessory's config. You only need to set it once so it matches your "Not wired" zones

**Comment by donavanbecker** [comment]
I know that in HomeKit enabled controllers, even disabled zones show. Could be that they choose to do though.

**Comment by donavanbecker** [comment]
![image](https://github.com/donavanbecker/homebridge-rainbird/assets/9875439/d4239a6c-be4d-4226-a0ba-2ef38cb1ba27)

**Comment by tbaur** [comment]
Yeah, the home app has enable/disabled, but it still shows. Have to catch it at the plugin and just not even create the accessory to begin with. It's kind of ok if you disable "show zones as valve accessories", still shows below the switches, but yes not as a switch. If you enable it, it's right there as an accessory and switch no matter. Could connect this with my other feature request around custom labelling ...the plugin UI configuration could have an enable/disable switch next to the custom label field. An idea anyway!

**Comment by mantorok1** [comment]
@donavanbecker, when I disable a sprinkler zone on my Home app the status of the zone says "Off" (not "Idle") and the switch disappears (i.e. the one inside the Irrigation System accessory)

@tbaur, the "show zones as valve accessories" option was added to overcome a bug introduced in an earlier version of iOS which intermittently hide the switches within the Irrigation system accessory. It creates valve accessories (outside of the Irrigation System) in the Home app. I was thinking of removing it now that Apple has fixed the bug. Do you still use it?

**Comment by tbaur** [comment]
It's still going to be valuable if you want to select a particular zone in an automation. Otherwise all you could select is a program. Same for a scene. I'd suggest transitioning the language from a bug workaround, to a normal feature and keep it.

**Comment by mantorok1** [comment]
@tbaur, are you able to check that disabling a zone in the Irrigation System accessory will hide the zone. It definitely works for me.
As for the valve accessories that are created when "show zones as valve accessories" is enabled, I can't find any "known" API requests that will return whether a zone is "Wired" or "Not Wired". So to remove any valve accessories for zones that are "Not Wired" we could create a new setting that will allow you to specify which zones you want valve accessories for. Would that solve the problem?

**Comment by tbaur** [comment]
Think I was mistaken about it showing not wired zones as accessories. You're right and I retested.

But glad all this came up and you mentioned removing "show zones as valve accessories". I'd want to ask to keep it as a go forward feature, and the extra suggest could be valuable in cases.

What I think I’m going to do -- show specific zones that I want to add automation for, or I can show them all (as I can right now). 

Then move all the program config into HomeKit automation ...and I wouldn't be limited to only 3 programs. I can create as many options as I want. Oh the added benefit, I could change the zone run order! I've never liked that I have to run the zones in numbered order in a program and can not sort them in the order I want.

So then the delay days feature also helps not needing to go back to the rainbird app for regular tasks.

**Comment by mantorok1** [comment]
I wasn't sure if anyone was using the "show zones as valve accessories" anymore but I'm happy to retain it if you find it useful.
To allow you to specify which zones you want to create as valve accessories I was thinking a new textbox were you provide a comma separated list of the zone numbers. If you want all zones then you can leave it blank.
e.g. If you just want zones 1, 4, 5 & 6 then you'd enter `1,4,5,6`

**Comment by tbaur** [comment]
Yep that works.

**Comment by mantorok1** [comment]
Hi @tbaur, there is a new beta (version 11) which should add this new setting. Please try it out and let us know if it solves your problem

**Comment by tbaur** [comment]
Looks good to me! thumbs up

**Comment by tbaur** [comment]
we're good, can release

**Comment by donavanbecker** [comment]
v1.10.0 has been released.
