### ISSUE TITLE
Feature Request: RC2 Support

### ISSUE THREAD

**Issue by bheyne666** [homebridge-plugins/homebridge-rainbird#491]
### Describe Your Problem

I have an RC2, I would love to use it with your app and have an option to store the irrigation log.

### Device & Model

RC2

### Node.js Version

18.16

### NPM Version

?

### Homebridge Version

1.6.1

### Homebridge Rainbird Plugin Version

1.11 beta

### Homebridge Config UI X Plugin Version

4.50.4

### Operating System

Ubuntu Focal Fossa (20.04.6 LTS)

**Comment by mantorok1** [comment]
Hi @bheyne666,
Are you talking about the Homebridge logs? If so they are usually written to the `homebridge.log` file in the folder where Homebridge is installed. If you scroll to the top of the Logs in Config UI it will display the location.

In my case they look like this:
```
Loading logs using native method...
File: /var/lib/homebridge/homebridge.log

[7/22/2023, 7:33:21 AM] [RainBird] Zone 2: Running [Time Remaining: 00:02:58]
[7/22/2023, 7:36:21 AM] [RainBird] Zone 2: Complete
[7/22/2023, 7:36:21 AM] [RainBird] Zone 3: Running [Time Remaining: 00:02:59]
[7/22/2023, 7:39:21 AM] [RainBird] Zone 3: Complete
[7/22/2023, 7:39:21 AM] [RainBird] Zone 4: Running [Time Remaining: 00:02:59]
[7/22/2023, 7:42:21 AM] [RainBird] Zone 4: Complete
[7/22/2023, 7:42:21 AM] [RainBird] Program A: Complete
```

**Comment by bheyne666** [comment]
Thank you. You learn something new everyday. :-)

I don't understand why Rainbird doesn't have this in their iOS app and it would be great if homekit would introduce a log.

I also have homey and that has a nice timeline. But a Rainbird app does not exist for homey.

Kind regards,
Bram

**Comment by bheyne666** [comment]
Beside that I would still love to see RC2 support (now it's only ARC8, I think.

**Comment by mantorok1** [comment]
Does the Rainbird plugin not support RC2? Most models should be supported but some may not show the time remaining properly as Rainbird seems to have implemented this differently for each model.

**Comment by donavanbecker** [comment]
v1.10.0 has been released.
