### ISSUE TITLE
Rain sensor accessory

### ISSUE THREAD

**Issue by tbaur** [homebridge-plugins/homebridge-rainbird#498]
### Problem

If moving automation from rainbird to Homekit, we need a rain sensor accessory

### Solution

Is it possible to create a rainbird rain sensor accessory via their API? it's an extra rainbird device/controller, that if enabled, programs will not run re the rainbird rain sensor collected enough rain to trigger aka it's rained. I'd like a Homekit accessory for this, so I can create an automation that says ...if rain delay (an existing accessory now) is negative and rain sensor is negative (Homekit accessory = off), then run. If 1 or both are positive (Homekit accessory = on), then skip.

### Additional context

This rainbird rain sensor accessory would pretty much 100% be updated by the rainbird controller and not really ever in Homekit, even if you could. But I might enable it in Homekit, by way of my weather station data pre-empting rain coming. I do this with the delay accessory, but that's not great for a few reasons.

**Comment by tbaur** [comment]
I should say that while the rain sensor is an extra device/controller, it's only interface is the main rainbird controller that you support. I am assuming there is an interface there, an API, that says "rain sensor enabled"

**Comment by tbaur** [comment]
ps. thanks again guys :) this is starting to become a fully flushed plugin and it just works.

**Comment by donavanbecker** [comment]
@tbaur I believe we already support this. In the device config select show rain sensor as leak sensor.

![image](https://github.com/donavanbecker/homebridge-rainbird/assets/9875439/17ebedff-081e-4f69-bde5-ca4fa6538c45)

**Comment by tbaur** [comment]
Uh, how did I miss that! Thanks, works :) My bad

**Comment by donavanbecker** [comment]
Your good!
