### ISSUE TITLE
Feature Request: add a rain sensor switch

### ISSUE THREAD

**Issue by tu00tf** [homebridge-plugins/homebridge-rainbird#50]
### Problem

As a rainbird user, I want to know the rain sensor status in HomeKit

### Solution

Add a switch sensor that polls the response from the get rain sensor status API

**Comment by tu00tf** [comment]
Welp, I used the template. Did I miss something?

**Comment by donavanbecker** [comment]
@tu00tf Sorry. I will reopen and check. Must not have something right.

**Comment by mantorok1** [comment]
@tu00tf, I think this request is similar to https://github.com/donavanbecker/homebridge-rainbird/issues/8 but using a switch instead of a leak sensor. We're thinking of also allowing a contact sensor as another option

**Comment by tu00tf** [comment]
Got it, thanks.

**Comment by donavanbecker** [comment]
@tu00tf I have added a contact sensor option to the latest beta. Can you give it a try?

**Comment by donavanbecker** [comment]
@tu00tf Option is available in latest version.

FYI, We have added an option to enable a contact sensor to be notified when a zone has run can you test it out?

Beta: 

[![npm version](https://badgen.net/npm/v/homebridge-rainbird/beta)](https://www.npmjs.com/package/homebridge-rainbird)
