### ISSUE TITLE
AxiosError: Request failed with status code 403Support Request: 

### ISSUE THREAD

**Issue by yaggayoyo** [homebridge-plugins/homebridge-rainbird#509]
### Describe Your Problem

I am getting - AxiosError: Request failed with status code 403

### Relevant log output

```shell
New to RainBird installed today but getting below errors.

11/30/2023, 9:00:37 AMRainbird BridgeRainBirdWARNINGRainBird controller request failed. [AxiosError: Request failed with status code 403]
11/30/2023, 9:00:37 AMRainbird BridgeRainBirdWARNINGFailed Request: [2] [ModelAndVersionRequest]
11/30/2023, 9:00:37 AMRainbird BridgeRainBirdWARNINGWill retry in 60 seconds
11/30/2023, 9:01:37 AMRainbird BridgeRainBirdWARNINGRainBird controller request

and

11/30/2023, 9:20:15 AMRainbird BridgeRainBirdWARNINGRainBird controller request failed. [AxiosError: Request failed with status code 430]
11/30/2023, 9:20:15 AMRainbird BridgeRainBirdWARNINGFailed Request: [2] [ModelAndVersionRequest]
11/30/2023, 9:20:15 AMRainbird BridgeRainBirdWARNINGWill retry in 60 seconds
```

### Config for homebridge-rainbird

```shell
{
    "platform": "RainBird",
    "name": "RainBird",
    "devices": [
        {
            "ipaddress": "10.0.x.x",
            "password": "xxxxx"
        }
    ]
}
```

### Device & Model

RC2 Series

### Node.js Version

16.20.2

### NPM Version

idk

### Homebridge Version

1.6

### Homebridge Rainbird Plugin Version

1.11.2

### Homebridge Config UI X Plugin Version

idk

### Operating System

HOOBS

**Comment by mantorok1** [comment]
Hi @yaggayoyo, a 403 error indicates that the server (i.e. RainBird controller) understands the request but can't provide additional access.
Please confirm that you have supplied the correct password to the plugin. It should be the same one you use to access the settings within the RainBird app on your iPhone.

**Comment by yaggayoyo** [comment]
Thank you! That worked. Entered special character originally.
