### ISSUE TITLE
Feature Request: sort zones by zone number rather than name

### ISSUE THREAD

**Issue by tu00tf** [homebridge-plugins/homebridge-rainbird#51]
### Problem

As a user, I want to see my zone switches sorted by index rather than name so I can see the run sequence

### Solution

If possible, sort the array of zone switches by index instead of name so they don't change order arbitrarily based on name changes

**Comment by mantorok1** [comment]
@tu00tf, I'm not sure the plugin has any control over the order of the zone switches, I think its the Home app that orders it. As a workaround you could prefix the zone number onto the name, such as:
1 - Front Lawn
2 - Back Lawn
@donavanbecker are you aware of a way to change the sort criteria for the zone switches?

**Comment by donavanbecker** [comment]
> @tu00tf, I'm not sure the plugin has any control over the order of the zone switches, I think its the Home app that orders it. As a workaround you could prefix the zone number onto the name, such as:
> 1 - Front Lawn
> 2 - Back Lawn
> @donavanbecker are you aware of a way to change the sort criteria for the zone switches?

@tu00tf 

the order is all sorted by alphabetical order. so I think if you did 

- 1 - Front Lawn 
- 2 - Back Lawn

It would keep that order but if you removed the numbers it would thens or it as

- Back Lawn
- Front Lawn

This is a HomeKit limitation.

**Comment by tu00tf** [comment]
Ok, got it. I did what you suggested. Closing.
