### ISSUE TITLE
Support Request: slow to respond/didn't respond

### ISSUE THREAD

**Issue by IWCaldwell** [homebridge-plugins/homebridge-rainbird#533]
### Describe Your Problem

Getting an error "The read handler for the characteristic 'On' didn't respond"

### Relevant log output

```shell
[06/07/2024, 16:32:05] [homebridge-rainbird] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.

[06/07/2024, 16:32:11] [homebridge-rainbird] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
```

### Config for homebridge-rainbird

```shell
{
    "name": "RainBird",
    "devices": [
        {
            "showRainSensor": true,
            "showValveSensor": true,
            "showProgramASwitch": true,
            "showProgramBSwitch": true,
            "showProgramCSwitch": true,
            "showStopIrrigationSwitch": true,
            "showZoneValve": true,
            "showDelayIrrigationSwitch": true,
            "irrigationDelay": 2,
            "syncTime": true,
            "showRequestResponse": true
        }
    ],
    "platform": "RainBird"
}
```

### Device & Model

Model: ESP-TM2, [Version: 2.10, Serial Number: ?????, Zones: [1,2,3,4,5,6]]

### Node.js Version

v20.15.0

### NPM Version

N/A

### Homebridge Version

v1.8.3

### Homebridge Rainbird Plugin Version

v2.0.3

### Homebridge Config UI X Plugin Version

v4.56.4

### Operating System

Raspbian GNU/Linux Bookworm (12)

**Comment by donavanbecker** [comment]
Have you tried setting up the plugin in a child bridge?

**Comment by IWCaldwell** [comment]
Yes, it is setup as a child bridge but still throwing the errors

**Comment by donavanbecker** [comment]
Is this happening on each Switch? or have you harrowed it down to a specific switch?
