### ISSUE TITLE
Accessories will not load

### ISSUE THREAD

**Issue by crashjnq** [homebridge-plugins/homebridge-rainbird#534]
### Describe Your Problem

I've installed the plugin and configured it, but nothing pulls into homebridge

### Relevant log output

```shell
[7/19/2024, 5:06:05 PM] [RainBird] Initializing RainBird platform...
[7/19/2024, 5:06:05 PM] Loading 19 accessories...
[7/19/2024, 5:13:40 PM] [RainBird] Initializing RainBird platform...
[7/19/2024, 5:13:40 PM] Loading 19 accessories...
```

### Config for homebridge-rainbird

```shell
"name": "RainBird",
    "devices": [
        {
            "ipaddress": 
            "password": 
            "external": false,
            "showRainSensor": true,
            "showValveSensor": true,
            "showProgramASwitch": true,
            "showProgramBSwitch": true,
            "showStopIrrigationSwitch": true,
            "showZoneValve": true,
            "includeZones": "1,2,3,4,5,6,7,8,9",
            "showDelayIrrigationSwitch": true,
            "syncTime": true,
            "refreshRate": 120,
            "logging": "standard"
        }
    ],
    "platform": "RainBird"
}
```

### Device & Model

EMS-TM2

### Node.js Version

v18.18.8

### NPM Version

v10.8.2

### Homebridge Version

v1.8.3

### Homebridge Rainbird Plugin Version

v2.0.3

### Homebridge Config UI X Plugin Version

v4.56.4

### Operating System

macOS

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-rainbird@beta/>=2.1.0-beta.9/orange)](https://www.npmjs.com/package/homebridge-august)

[Click here to find out how to install Beta](https://github.com/donavanbecker/homebridge-august/wiki/Beta-Version)

**Comment by rvniekerk** [comment]
I have the same problem. Installed the plugin last week running from my MacBook with no issues. Transferred the server to my Raspberry Pi this week and can't get it going - all my other plugins works fine. 

It pulls the bridge into Homekit with no issues, but none of the accessories are pulled in. Also not into the Homebridge accessories page. 

Would love to use this if I can figure out how to get it going again.

**Comment by donavanbecker** [comment]
> I have the same problem. Installed the plugin last week running from my MacBook with no issues. Transferred the server to my Raspberry Pi this week and can't get it going - all my other plugins works fine. 
> 
> It pulls the bridge into Homekit with no issues, but none of the accessories are pulled in. Also not into the Homebridge accessories page. 
> 
> Would love to use this if I can figure out how to get it going again. 

Please open your own issue as this is probably not the same issue you are having.

**Comment by rvniekerk** [comment]
> > I have the same problem. Installed the plugin last week running from my MacBook with no issues. Transferred the server to my Raspberry Pi this week and can't get it going - all my other plugins works fine. 
> > 
> > It pulls the bridge into Homekit with no issues, but none of the accessories are pulled in. Also not into the Homebridge accessories page. 
> > 
> > Would love to use this if I can figure out how to get it going again. 
> 
> Please open your own issue as this is probably not the same issue you are having.

> Ok sure - but got mine resolved in the end.
