### ISSUE TITLE
Bug: Device Removed After Upgrade

### ISSUE THREAD

**Issue by equals42** [homebridge-plugins/homebridge-rainbird#538]
### Describe The Bug

Device deleted on upgrade and password section missing

### To Reproduce

Create a new device with IP

### Expected behavior

I expect to be able to create a device and not see errors about a missing password

### Relevant log output

```shell
Initial logs from after upgrade of plugin

[11/09/2024, 10:32:39] [RainBird] Verify Config, Error Message: The devices config section is missing from the config. This device will be skipped., Submit Bugs Here: https://bit.ly/homebridge-rainbird-bug-report
[11/09/2024, 10:32:39] [RainBird] Loading accessory from cache: 7
Setup Payload:
X-HM://0024WZTN83F00
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ XXX-XX-XXX │     
    └────────────┘     
                       
[11/09/2024, 10:32:39] [RainBird] Failed to Discover Devices, "this.config.devices is not iterable"

After config of new device in plugin:

[11/09/2024, 10:38:09] [RainBird] Initializing RainBird platform...
[11/09/2024, 10:38:11] [RainBird] Verify Config, Error Message: The devices config section is missing the "Password" in the config, and will be skipped., Submit Bugs Here: https://bit.ly/homebridge-rainbird-bug-report
[11/09/2024, 10:38:11] [RainBird] Loading accessory from cache: 7
Setup Payload:
X-HM://0024WZTN83F00
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ XXX-XX-XXX │     
    └────────────┘     
                       
[11/09/2024, 10:38:11] [RainBird] Failed to Discover Devices, "Cannot read properties of undefined (reading 'refreshRate')"
```

### Config for homebridge-rainbird

```shell
{
    "name": "RainBird",
    "devices": [
        {
            "ipaddress": "10.0.X.XX",
            "showRainSensor": true,
            "showValveSensor": true,
            "showDelayIrrigationSwitch": true,
            "syncTime": false
        }
    ],
    "platform": "RainBird"
}
```

### Device & Model

Rainbird N/A

### Node.js Version

v20.9.0

### NPM Version

unknown

### Homebridge Version

1.8.4

### Homebridge Rainbird Plugin Version

v2.1.0

### Homebridge Config UI X Plugin Version

v4.58.0

### Operating System

Raspian

**Comment by donavanbecker** [comment]
@equals42 What version did you upgrade from?

**Comment by equals42** [comment]
I looked through the logs and there seems to be errors back to July on 2.0.2 so maybe it wasn’t this upgrade. I’ve been out of town most of the summer and didn’t mess with the Rainbird in Homekit so it could have happened on a 1.x to 2.x upgrade. It was functional in spring IIRC. Sorry if this is unhelpful.As of now, I cannot seem to enter a password in the device setup so it is not functional[11/09/2024, 10:38:11] [RainBird] Verify Config, Error Message: The devices config section is missing the "Password" in the config, and will be skipped., Submit Bugs Here: https://bit.ly/homebridge-rainbird-bug-report[11/09/2024, 10:38:11] [RainBird] Loading accessory from cache:

**Comment by donavanbecker** [comment]
Please respond directly on GitHub as you are filling the comments with extra text.

**Comment by donavanbecker** [comment]
Can you send a screenshot of what your UI looks like?

**Comment by equals42** [comment]
![IMG_0129](https://github.com/user-attachments/assets/98b4bbbd-c36b-4343-9b7c-f830e75c8543)

**Comment by donavanbecker** [comment]
Does the password show if you type in the device name?

**Comment by donavanbecker** [comment]
Not sure how the password field got hidden on the UI. That wouldn't cause the password to be deleted, but v2.1.1 adds it back to the UI.

**Comment by equals42** [comment]
The password field is back. Once it was entered, the sprinkler worked again. There was some error about ESP-me having invalid characters but it doesn’t seem to impact its functionality.

Thanks.
