### ISSUE TITLE
Support Request: getting an error message in Homebridge

### ISSUE THREAD

**Issue by dikodahan** [homebridge-plugins/homebridge-rainbird#76]
### Describe Your Problem

Cannot see my rainbird zones in Homekit 

### Relevant log output

```shell
It seems that there is an issue that is causing this to fail.
I am receiving this error message every 60 seconds:

[10/20/2021, 10:48:09 AM] [RainBird] Will retry in 60 seconds
[10/20/2021, 10:49:09 AM] [RainBird] RainBird controller request failed. [Error: Invalid Response [Status: 420, Text: Enhance Your Calm]]

I enabled debug mode thinking it may help you in solving the issue.
```

### Config for homebridge-rainbird

```shell
{
            "name": "RainBird",
            "devices": [
                {
                    "ipaddress": "xxx.xxx.xxx.xxx",
                    "password": "xxxxxxxxx"
                }
            ],
            "options": {
                "debug": true
            },
            "platform": "RainBird"
        }
```

### Screenshots

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/38052895/138117711-abf5e20c-11a6-4b0b-a022-c8b84e012e6d.png">

### Device & Model

ESP-Me

### Node.js Version

v14.18.1

### NPM Version

v8.1.0

### Homebridge Version

v1.3.5

### Homebridge Rainbird Plugin Version

v.1.3.0

### Homebridge Config UI X Plugin Version

v4.41.2

### Operating System

Rasbian

**Comment by mantorok1** [comment]
Wow I'd never heard of HTTP Error code 420. Looks like its an unofficial code created by twitter to indicate that they were putting restrictions on the total number of requests a client may do within a time period (see https://evertpot.com/http/420-enhance-your-calm)

Does the plugin work ok for a while before the above error occurs?

One thing you can do is put Homebridge into DEBUG mode which will show additional debug messages in the log. Could you post these debug messages up to and including the 420 errors you're seeing.

**Comment by mantorok1** [comment]
Hi @dikodahan, could you please provide the above requested details so we can try to assist in getting it working for you.

Also, have you tried the latest version (1.4.0) of the plugin to see if it helps?

**Comment by dikodahan** [comment]
After a reset to the LNK controller and an update to the latest 1.5.1 I can share that the issue is resolved.
Thank you!

**Comment by donavanbecker** [comment]
@dikodahan Awesome!
